[entryPoints]
[entryPoints.http]
address = ":80"
[entryPoints.http.http.redirections]
[entryPoints.http.http.redirections.entryPoint]
to = "https"

[entryPoints.https]
address = ":443"

[api]
dashboard = true
insecure = true

[ping]

[providers]
[providers.docker]
exposedByDefault = false
swarmMode = true
[providers.file]
directory = "/etc/traefik/files"
watch = true

[certificatesResolvers.letsencrypt.acme]
email = "jochen.zehnder@gmail.com"
storage = "/certs/acme.json"
[certificatesResolvers.letsencrypt.acme.httpChallenge]
entryPoint = "http"

[log]
level = "INFO"

[metrics]
[metrics.prometheus]
