version: "3.9"

services:
  traefik:
    image: "elft3r/swarm-traefik:latest"
    container_name: "traefik"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
      - target: 443
        published: 443
        protocol: tcp
        mode: ingress
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8080/ping || exit 1"
      interval: 10s
      timeout: 10s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
          - traefik.enable=false

networks:
  traefik:
    driver: overlay
    name: traefik
