version: "3.9"

services:
  traefik:
    image: "elft3r/swarm-traefik:latest"
    ports:
      - target: 80
        published: 80
        mode: ingress
      - target: 443
        published: 443
        mode: ingress
      - target: 8080
        published: 8090
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: certs-vol
        target: /certs
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8080/ping || exit 1"
      interval: 10s
      timeout: 10s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == elft3r-pi-200
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
      labels:
          - traefik.enable=false
    networks:
      - traefik

networks:
  traefik:
    driver: overlay
    name: traefik

volumes:
  certs-vol:
