[http.routers]
[http.routers.nas]
rule = "Host(`nas.new-bridge.dev`)"
service = "nas"
[http.routers.nas.tls]
certResolver = "letsencrypt"

[http.services]
[http.services.nas.loadBalancer]
[[http.services.nas.loadBalancer.servers]]
url = "http://192.168.1.120:5000/"
