---
name: Deploy Traefik Stack

on:
  push:
    branches: [main]
    paths: [traefik/**, .github/workflows/traefik-deploy.yml]

jobs:
  deploy:
    name: Deploy Traefik Stack
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Deploy Traefik Stack
        run: |
          docker stack deploy -c traefik/traefik-stack.yml traefik
